version: "2"
linters:
  enable:
    - unused
    - gocritic
    - misspell
  disable:
    - errcheck
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1001"
formatters:
  enable:
    - gofmt
    - goimports
