version: "3"

env:
  GOTOOLCHAIN: local
  GOPROXY: direct
  GONOSUMCHECK: "*"
  GONOSUMDB: "*"

tasks:
  test:
    cmds:
      - tape
    
  coverage:
    cmds:
      - tape --coverage
    
  report:
    cmds:
      - tape --coverage --report
  
  test:go:
    cmds:
      - go test $(go list ./... | grep -v "^coderaiser/indra$")

  coverage:go:
    cmds:
      - go test -coverprofile=c.out $(go list ./... | grep -v "^coderaiser/indra$")
      - go tool cover -func=c.out | grep -v "100.0%" | grep -v "^total"

  build:
    cmds:
      - go build -o indra ./cmd/indra

  lint:
    deps: [build]
    cmds:
      - ./indra .
      - golangci-lint run

  fix:lint:
    deps: [build]
    cmds:
      - ./indra --fix .
      - golangci-lint run --fix

  clean:
    cmds:
      - rm -f indra c.out
