version: "3"
tasks:
  test:
    cmds:
      - GOTOOLCHAIN=local GOPROXY=off go test ./...
  build:
    cmds:
      - go build -o indra ./cmd/indra
  lint:
    cmds:
      - go run ./cmd/indra ./...
  fix:lint:
    cmds:
      - go run ./cmd/indra --fix ./...
  clean:
    cmds:
      - rm -f indra c.out
